name: Build and Push Docker Image

# Kích hoạt workflow khi có sự kiện release được tạo
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước checkout mã nguồn từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Cài đặt các dependencies cần thiết để build
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      # Cài đặt Docker Buildx để build image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Đăng nhập vào DockerHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build ứng dụng sử dụng Makefile
      - name: Build Go application
        run: make buildwithview

      # Build và push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spurt-cms:${{ github.event.release.tag_name }}
          file: Dockerfile

      # In ra thành công khi build và push hoàn tất
      - name: Docker image successfully built and pushed
        run: echo "Docker image with tag ${{ github.event.release.tag_name }} has been pushed successfully!"
