name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Go application
        run: make buildwithview

      # Build và push Docker multi-architecture images
      - name: Build and Push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64    # Hỗ trợ cả amd64 và arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/spurt-cms:${{ github.event.release.tag_name }}
          file: Dockerfile

      - name: Docker image successfully built and pushed
        run: echo "Docker image with tag ${{ github.event.release.tag_name }} has been pushed successfully!"
